import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/layout/header";
import { IBM_Plex_Sans, Playfair_Display } from "next/font/google";
import { Footer } from "@/components/layout/footer";
import { SessionProvider } from "next-auth/react"
import { AuthProvider } from "@/lib/auth";

const ibmPlexSans = IBM_Plex_Sans({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
  variable: '--font-ibm-plex-sans'
})

const playfairDisplay = Playfair_Display({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
  variable: '--font-playfair-display'
})

export const metadata: Metadata = {
  title: "Web Nepal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${ibmPlexSans.variable} ${playfairDisplay.variable}`}>
        <Header />
        <SessionProvider>
          <AuthProvider>{children}</AuthProvider>
        </SessionProvider>
        <Footer />
      </body>
    </html>
  );
}
